---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  # Updates (cron)
  - shell: crontab -l
    register: stereum_crontab
  - name: Check cron for update check
    assert:
      that:
      - stereum_crontab.stdout.find("update-check.yaml") != -1 # there should be update checks
      - stereum_crontab.stdout.find("unattended-update.sh") == -1 # there shouldn't be unatteded updates