---
- name: Generate stereum user password
  set_fact:
    stereum_user_pw_autogen: "{{ lookup('password', './stereum-pwd chars=ascii_letters,digits,hexdigits,punctuation length=64') | password_hash('sha512') }}"

- name: Add stereum user
  user:
    name: "{{ stereum.defaults.os_user }}"
    password: "{{ stereum_user_pw_autogen }}"
    force: no
  changed_when: "'molecule-notest' not in ansible_skip_tags"

- name: Add stereum user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ stereum.defaults.os_user }} ALL"
    line: "{{ stereum.defaults.os_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present

- name: Add stereum user to docker group
  user:
    name: "{{ stereum.defaults.os_user }}"
    groups: docker
    append: yes