---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest # noqa 403 package-latest
  changed_when: "'molecule-notest' not in ansible_skip_tags"

- name: Install epel-release
  yum:
    name: epel-release
    state: present