---
- name: Prepare
  hosts: all
  roles:
    - role: '../'
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml

  tasks:
    - name: Install python for Ansible (Ubuntu)
      raw: apt update && apt install -y pip
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_distribution == "CentOS"

    - include_role:
        name: "setup"

    - include_role:
        name: "configure-firewall"

    - name: Write service configuration lighthouse
      copy:
        dest: "/etc/stereum/services/9024aec6-12a8-456a-8096-ee7ef6f67167.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          command: []
          entrypoint:
          - /opt/app/start/beacon.sh
          env:
            DATADIR: /opt/app/beacon
            DEBUG_LEVEL: info
            ETH1_NODES: http://stereum-geth-25df0439-80e6-4afe-8876-72d7718035c3:8545
            NETWORK: prater
            SLASHERDIR: /opt/app/slasher
            SLASHER_DB_SIZE: '16'
          id: 9024aec6-12a8-456a-8096-ee7ef6f67167
          image: stereum/lighthouse:v2.0.1-47
          name: lighthouse
          ports:
          - 0.0.0.0:9000:9000/tcp
          - 0.0.0.0:9000:9000/udp
          volumes:
          - /opt/stereum/lighthouse/beacon:/opt/app/beacon
          - /opt/stereum/lighthouse/slasher:/opt/app/slasher
          user: 2000
      become: yes

    - name: Write service configuration geth
      copy:
        dest: "/etc/stereum/services/25df0439-80e6-4afe-8876-72d7718035c3.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          command: "geth --goerli --http --http.port=8545 --http.addr=0.0.0.0 --http.vhosts='*' --allow-insecure-unlock --http.api='db,eth,net,web3,personal'"
          entrypoint: []
          env:
            STEREUM_DUMMY: foobar
          id: 25df0439-80e6-4afe-8876-72d7718035c3
          image: ethereum/client-go:v1.10.11
          name: geth
          ports:
          - 0.0.0.0:30303:30303/tcp
          - 0.0.0.0:30303:30303/udp
          volumes:
          - /opt/stereum/geth:/root/.ethereum
          user: root
      become: yes
