---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python for Ansible (Ubuntu)
      raw: apt update && apt install -y pip
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_distribution == "CentOS"
